### PR TITLE
Fix race condition and remove unneccesery for loop

### LINKED ISSUE #8: panic: send on closed channel
```
goroutine 33 [running]:
github.com/ahmetask/worker.(*Pool).EnqueueWithTimeout.func1()
        /root/go/src/github com/ahmetask/worker/dispatcher.go:106 +0x36
created by time.goFunc
        /usr/local/go/src/time/sleep.go:166 +0x45
```

test case:

```
q.internalQueue <- job
return
run defer
t.Stop()
close(ch)
```

at the same time timer is fired just by timeout. It's race condition: defer vs timer's func
`ch <- false // but ch is closed yet`

timer.Stop doesn't stop timer really, it marks it as stopped only and timer will be deleted by goroutine that created that timer.

[time.go deltimer func with comment](https://cs.opensource.google/go/go/+/master:src/runtime/time.go;l=306)

### PR DESCRIPTION
**Pull request by ahmetask**
resolves https://github.com/ahmetask/worker/issues/8 and https://github.com/ahmetask/worker/issues/7

### CODE REVIEW

**Comment by waffleboot** [comment]
@ahmetask `ch` is unbuffered channel, so it looks like timer's goroutine will be leaked as nobody will read bool from that channel

**Comment by waffleboot** [comment]
@ahmetask it's better to close channel in timer's func
in this case (on timeout) select{} will be unblocked and we return false and defer will just remove our timer from timers set
in successfull sending job to queue we run defer and timer will be freed from timers set by stopping and in case of race condition we just close channel but it doesn't matter or we never will close channel (never see timeout) but it doesn't matter also.

**Comment by ahmetask** [comment]
thanks its good idea. I added

**Comment by waffleboot** [comment]
@ahmetask, I mean you have to delete `ch <- false` in timer func at all. Closing channel will not be invoked at all if it stucks before sending to nobody-read channel. If nobody reads unbuffered channel when sending will be blocked.

> @ahmetask `ch` is unbuffered channel, so it looks like timer's goroutine will be leaked as nobody will read bool from that channel

**Comment by ahmetask** [comment]
I will do some testing. I will analyse at the weekend. 
I don't think the same as you.

**Comment by ahmetask** [comment]
Hi @waffleboot  could you please run below code and visit http://localhost:8080/debug/pprof/

Thread count is fixed and no memory leak. GC deletes unused(unclosed) channel. Let me know if you have any questions.  Each timer has own channel so no blocking. ch read by select statement. If write operation performed if no one read that channel its not a problem because it is not used so GC will delete it. 

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	_ "net/http/pprof"
	"time"
)

func EnqueueWithTimeout(m chan bool) bool {

	ch := make(chan bool)
	t := time.AfterFunc(1*time.Millisecond, func() { ch <- false })
	defer func() {
		t.Stop()
	}()

	select {
	case m <- true:
		return true
	case <-ch:
		return false
	}
}

func main() {

	go func() {
		log.Println(http.ListenAndServe("localhost:8080", nil))
	}()

	ch := make(chan bool, 2)

	for {
		ret := EnqueueWithTimeout(ch)

		if ret {
			fmt.Println("enqueue")
		}
	}
}

```

**Comment by waffleboot** [comment]
Hi @asikahmet 

```
go func() {
	log.Println(http.ListenAndServe("localhost:8080", nil))
}()
```

could be rewriten as

```
go log.Println(http.ListenAndServe("localhost:8080", nil))
```

**Comment by waffleboot** [comment]
@ahmetask 

let's add delays, I always can do it because of threads random preemption and read sent values
w/o reading we always will exit by timeout

```
var _x int

func EnqueueWithTimeout(out chan<- bool) bool {

	c := make(chan int)
	t := time.AfterFunc(1*time.Millisecond, func() {
		// !!!!!!!!!!!!!!!! add delay !!!!!!!!!!!!!!!!!!!!!!
		for i := 0; i < 1e9; i++ {
			_x = i
		}
		c <- 1
	})
	defer func() {
		// !!!!!!!!!!!!!!!! add delay !!!!!!!!!!!!!!!!!!!!!!
		for i := 0; i < 1e9; i++ {
			_x = i
		}
		t.Stop()
	}()

	select {
	case out <- true:
		return true
	case <-c:
		return false
	}
}

func main() {
	go func() {
		log.Println(http.ListenAndServe("localhost:8080", nil))
	}()
	ch := make(chan bool, 2)
	for {
		if EnqueueWithTimeout(ch) {
			fmt.Println("enqueue")
			// !!!!!!!!!!!!!!!! read !!!!!!!!!!!!!!!!!!!!!!
			<-ch
		}
	}
}

```

Now I see in /debug/pprof:

1. increasing count of goroutines (270+ goroutines)
2. full goroutine stack dump =>

```
goroutine 114 [chan send]:
main.EnqueueWithTimeout.func1()
	/Users/yangand/Workspace/ahmetask/example/main.go:20 +0x4d
created by time.goFunc
	/usr/local/Cellar/go/1.16.6/libexec/src/time/sleep.go:180 +0x45
```

I think it still doesn't work, sorry.
Every time you are going to run goroutine (explicit by `go` or timer will do it for you) you have to understand how to stop it. I don't understand how timer's `ch <- false` will be stopped except ghostly hope that t.Stop will do it fo us.

Just close channel in timer goroutine.

**Comment by ahmetask** [comment]
@waffleboot  bounded channel works.  I think it's fine as it is. Thanks
```go 
package main

import (
	"fmt"
	"log"
	"net/http"
	_ "net/http/pprof"
	"time"
)

var _x int

func EnqueueWithTimeout(m chan bool) bool {

	ch := make(chan bool, 1)
	t := time.AfterFunc(1*time.Millisecond, func() {
		// !!!!!!!!!!!!!!!! add delay !!!!!!!!!!!!!!!!!!!!!!
		for i := 0; i < 1e9; i++ {
			_x = i
		}
		ch <- false
		fmt.Println("exit timeout")
	})
	defer func() {
		// !!!!!!!!!!!!!!!! add delay !!!!!!!!!!!!!!!!!!!!!!
		for i := 0; i < 1e9; i++ {
			_x = i
		}
		t.Stop()
                	fmt.Println("exit")
	}()

	select {
	case m <- true:
		return true
	case <-ch:
		return false
	}
}

func main() {

	go func() {
		log.Println(http.ListenAndServe("localhost:8080", nil))
	}()

	ch := make(chan bool, 2)

	for {
		ret := EnqueueWithTimeout(ch)

		if ret {
			<-ch
			fmt.Println("enqueue")
		} else  {
			fmt.Println("not")
		}
	}
}

```

**Comment by waffleboot** [comment]
Hi @ahmetask 

Yes, you are right, bounded channel is fine in most cases also, may be even better than closing channel, you are right. Thank you too.

**Pull request merged**
